DROP TABLE T_CLYVO_HISTORICO CASCADE CONSTRAINTS;
DROP TABLE T_CLYVO_CONSULTA CASCADE CONSTRAINTS;
DROP TABLE T_CLYVO_VACINA_ANIMAL CASCADE CONSTRAINTS;
DROP TABLE T_CLYVO_DOENCA_ANIMAL CASCADE CONSTRAINTS;
DROP TABLE T_CLYVO_VACINA CASCADE CONSTRAINTS;
DROP TABLE T_CLYVO_DOENCA CASCADE CONSTRAINTS;
DROP TABLE T_CLYVO_ANIMAL CASCADE CONSTRAINTS;
DROP TABLE T_CLYVO_VETERINARIO CASCADE CONSTRAINTS;
DROP TABLE T_CLYVO_RESPONSAVEL CASCADE CONSTRAINTS;

CREATE TABLE T_CLYVO_RESPONSAVEL (
    id_responsavel NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_responsavel VARCHAR2(50) NOT NULL,
    cpf VARCHAR2(14),
    dt_nascimento DATE,
    email VARCHAR2(50) NOT NULL,
    num_celular VARCHAR2(20) NOT NULL
);

COMMENT ON TABLE T_CLYVO_RESPONSAVEL IS 'Pessoa responsavel legal por um ou mais animais cadastrados no sistema';
COMMENT ON COLUMN T_CLYVO_RESPONSAVEL.id_responsavel IS 'Identificador unico do responsavel';
COMMENT ON COLUMN T_CLYVO_RESPONSAVEL.nm_responsavel IS 'Nome completo do responsavel';
COMMENT ON COLUMN T_CLYVO_RESPONSAVEL.cpf IS 'CPF do responsavel';
COMMENT ON COLUMN T_CLYVO_RESPONSAVEL.dt_nascimento IS 'Data de nascimento do responsavel';
COMMENT ON COLUMN T_CLYVO_RESPONSAVEL.email IS 'E-mail de contato do responsavel';
COMMENT ON COLUMN T_CLYVO_RESPONSAVEL.num_celular IS 'Telefone de contato do responsavel';

CREATE TABLE T_CLYVO_VETERINARIO (
    id_veterinario NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_veterinario VARCHAR2(50) NOT NULL,
    cpf VARCHAR2(14),
    dt_nascimento DATE,
    email VARCHAR2(50),
    num_celular VARCHAR2(20) NOT NULL,
    especialidade VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE T_CLYVO_VETERINARIO IS 'Profissional veterinario responsavel por consultas';
COMMENT ON COLUMN T_CLYVO_VETERINARIO.id_veterinario IS 'Identificador unico do veterinario';
COMMENT ON COLUMN T_CLYVO_VETERINARIO.nm_veterinario IS 'Nome completo do veterinario';
COMMENT ON COLUMN T_CLYVO_VETERINARIO.cpf IS 'CPF do veterinario';
COMMENT ON COLUMN T_CLYVO_VETERINARIO.dt_nascimento IS 'Data de nascimento do veterinario';
COMMENT ON COLUMN T_CLYVO_VETERINARIO.email IS 'E-mail de contato do veterinario';
COMMENT ON COLUMN T_CLYVO_VETERINARIO.num_celular IS 'Telefone de contato do veterinario';
COMMENT ON COLUMN T_CLYVO_VETERINARIO.especialidade IS 'Area de especializacao do veterinario';

CREATE TABLE T_CLYVO_ANIMAL (
    id_animal NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_animal VARCHAR2(50),
    idade NUMBER(10,0),
    especie VARCHAR2(50),
    raca VARCHAR2(50),
    sexo VARCHAR2(1),
    dt_nascimento DATE,
    peso NUMBER,
    fk_id_responsavel NUMBER(19,0),
    CONSTRAINT fk_animal_responsavel FOREIGN KEY (fk_id_responsavel) REFERENCES T_CLYVO_RESPONSAVEL(id_responsavel)
);

COMMENT ON TABLE T_CLYVO_ANIMAL IS 'Animal domestico cadastrado no sistema, vinculado a um responsavel';
COMMENT ON COLUMN T_CLYVO_ANIMAL.id_animal IS 'Identificador unico do animal';
COMMENT ON COLUMN T_CLYVO_ANIMAL.nm_animal IS 'Nome do animal';
COMMENT ON COLUMN T_CLYVO_ANIMAL.idade IS 'Idade do animal em anos';
COMMENT ON COLUMN T_CLYVO_ANIMAL.especie IS 'Especie do animal';
COMMENT ON COLUMN T_CLYVO_ANIMAL.raca IS 'Raca do animal';
COMMENT ON COLUMN T_CLYVO_ANIMAL.sexo IS 'Sexo do animal: M para macho, F para femea';
COMMENT ON COLUMN T_CLYVO_ANIMAL.dt_nascimento IS 'Data de nascimento do animal';
COMMENT ON COLUMN T_CLYVO_ANIMAL.peso IS 'Peso atual do animal em quilogramas';
COMMENT ON COLUMN T_CLYVO_ANIMAL.fk_id_responsavel IS 'Chave estrangeira para o responsavel legal do animal';

CREATE TABLE T_CLYVO_DOENCA (
    id_doenca NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_doenca VARCHAR2(50),
    tipo VARCHAR2(50),
    contagiosidade VARCHAR2(1),
    descricao CLOB
);

COMMENT ON TABLE T_CLYVO_DOENCA IS 'Doenca cadastrada no catalogo do sistema';
COMMENT ON COLUMN T_CLYVO_DOENCA.id_doenca IS 'Identificador unico da doenca';
COMMENT ON COLUMN T_CLYVO_DOENCA.nm_doenca IS 'Nome da doenca';
COMMENT ON COLUMN T_CLYVO_DOENCA.tipo IS 'Tipo ou categoria da doenca';
COMMENT ON COLUMN T_CLYVO_DOENCA.contagiosidade IS 'Indica se a doenca e contagiosa: S ou N';
COMMENT ON COLUMN T_CLYVO_DOENCA.descricao IS 'Descricao detalhada da doenca';

CREATE TABLE T_CLYVO_VACINA (
    id_vacina NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_vacina VARCHAR2(50),
    tipo VARCHAR2(50),
    descricao CLOB
);

COMMENT ON TABLE T_CLYVO_VACINA IS 'Vacina cadastrada no catalogo do sistema';
COMMENT ON COLUMN T_CLYVO_VACINA.id_vacina IS 'Identificador unico da vacina';
COMMENT ON COLUMN T_CLYVO_VACINA.nm_vacina IS 'Nome da vacina';
COMMENT ON COLUMN T_CLYVO_VACINA.tipo IS 'Tipo ou categoria da vacina';
COMMENT ON COLUMN T_CLYVO_VACINA.descricao IS 'Descricao detalhada da vacina';

CREATE TABLE T_CLYVO_DOENCA_ANIMAL (
    id_doenca_animal NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_diagnostico DATE,
    gravidade VARCHAR2(50),
    status VARCHAR2(50),
    observacoes CLOB,
    fk_id_animal NUMBER(19,0),
    fk_id_doenca NUMBER(19,0),
    CONSTRAINT fk_doencaanimal_animal FOREIGN KEY (fk_id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal),
    CONSTRAINT fk_doencaanimal_doenca FOREIGN KEY (fk_id_doenca) REFERENCES T_CLYVO_DOENCA(id_doenca)
);

COMMENT ON TABLE T_CLYVO_DOENCA_ANIMAL IS 'Registro de diagnostico de uma doenca em um animal especifico';
COMMENT ON COLUMN T_CLYVO_DOENCA_ANIMAL.id_doenca_animal IS 'Identificador unico do diagnostico';
COMMENT ON COLUMN T_CLYVO_DOENCA_ANIMAL.dt_diagnostico IS 'Data em que o diagnostico foi realizado';
COMMENT ON COLUMN T_CLYVO_DOENCA_ANIMAL.gravidade IS 'Gravidade do quadro diagnosticado';
COMMENT ON COLUMN T_CLYVO_DOENCA_ANIMAL.status IS 'Status do tratamento da doenca';
COMMENT ON COLUMN T_CLYVO_DOENCA_ANIMAL.observacoes IS 'Observacoes clinicas sobre o diagnostico';
COMMENT ON COLUMN T_CLYVO_DOENCA_ANIMAL.fk_id_animal IS 'Chave estrangeira para o animal diagnosticado';
COMMENT ON COLUMN T_CLYVO_DOENCA_ANIMAL.fk_id_doenca IS 'Chave estrangeira para a doenca diagnosticada';

CREATE TABLE T_CLYVO_VACINA_ANIMAL (
    id_vacina_animal NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_doses NUMBER(10,0),
    frequencia_aplicacao NUMBER(10,0),
    dt_receita DATE,
    fk_id_vacina NUMBER(19,0),
    fk_id_animal NUMBER(19,0),
    CONSTRAINT fk_vacinaanimal_vacina FOREIGN KEY (fk_id_vacina) REFERENCES T_CLYVO_VACINA(id_vacina),
    CONSTRAINT fk_vacinaanimal_animal FOREIGN KEY (fk_id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

COMMENT ON TABLE T_CLYVO_VACINA_ANIMAL IS 'Registro de aplicacao de uma vacina em um animal especifico';
COMMENT ON COLUMN T_CLYVO_VACINA_ANIMAL.id_vacina_animal IS 'Identificador unico da aplicacao';
COMMENT ON COLUMN T_CLYVO_VACINA_ANIMAL.num_doses IS 'Numero de doses ja aplicadas';
COMMENT ON COLUMN T_CLYVO_VACINA_ANIMAL.frequencia_aplicacao IS 'Intervalo em dias entre uma dose e outra';
COMMENT ON COLUMN T_CLYVO_VACINA_ANIMAL.dt_receita IS 'Data em que a vacina foi aplicada';
COMMENT ON COLUMN T_CLYVO_VACINA_ANIMAL.fk_id_vacina IS 'Chave estrangeira para a vacina aplicada';
COMMENT ON COLUMN T_CLYVO_VACINA_ANIMAL.fk_id_animal IS 'Chave estrangeira para o animal vacinado';

CREATE TABLE T_CLYVO_CONSULTA (
    id_consulta NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_agendamento DATE,
    dt_consulta DATE NOT NULL,
    fk_id_animal NUMBER(19,0),
    fk_id_veterinario NUMBER(19,0),
    CONSTRAINT fk_consulta_animal FOREIGN KEY (fk_id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal),
    CONSTRAINT fk_consulta_veterinario FOREIGN KEY (fk_id_veterinario) REFERENCES T_CLYVO_VETERINARIO(id_veterinario)
);

COMMENT ON TABLE T_CLYVO_CONSULTA IS 'Consulta veterinaria agendada para um animal com um veterinario';
COMMENT ON COLUMN T_CLYVO_CONSULTA.id_consulta IS 'Identificador unico da consulta';
COMMENT ON COLUMN T_CLYVO_CONSULTA.dt_agendamento IS 'Data em que a consulta foi agendada';
COMMENT ON COLUMN T_CLYVO_CONSULTA.dt_consulta IS 'Data em que a consulta sera realizada';
COMMENT ON COLUMN T_CLYVO_CONSULTA.fk_id_animal IS 'Chave estrangeira para o animal da consulta';
COMMENT ON COLUMN T_CLYVO_CONSULTA.fk_id_veterinario IS 'Chave estrangeira para o veterinario responsavel';

CREATE TABLE T_CLYVO_HISTORICO (
    id_historico NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_historico CLOB,
    dt_criacao_historico DATE,
    num_consultas_clyvo NUMBER,
    fk_id_consulta NUMBER(19,0),
    fk_id_animal NUMBER(19,0),
    CONSTRAINT fk_historico_consulta FOREIGN KEY (fk_id_consulta) REFERENCES T_CLYVO_CONSULTA(id_consulta),
    CONSTRAINT fk_historico_animal FOREIGN KEY (fk_id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

COMMENT ON TABLE T_CLYVO_HISTORICO IS 'Historico clinico gerado a partir de uma consulta realizada';
COMMENT ON COLUMN T_CLYVO_HISTORICO.id_historico IS 'Identificador unico do historico';
COMMENT ON COLUMN T_CLYVO_HISTORICO.link_historico IS 'Link de acesso ao registro ou gravacao da consulta';
COMMENT ON COLUMN T_CLYVO_HISTORICO.dt_criacao_historico IS 'Data em que o historico foi gerado';
COMMENT ON COLUMN T_CLYVO_HISTORICO.num_consultas_clyvo IS 'Numero de consultas registradas no sistema para o animal';
COMMENT ON COLUMN T_CLYVO_HISTORICO.fk_id_consulta IS 'Chave estrangeira para a consulta de origem';
COMMENT ON COLUMN T_CLYVO_HISTORICO.fk_id_animal IS 'Chave estrangeira para o animal do historico';

INSERT INTO T_CLYVO_RESPONSAVEL (nm_responsavel, cpf, dt_nascimento, email, num_celular)
VALUES ('Ana Beatriz Souza', '529.982.247-25', DATE '1990-04-12', 'ana.souza@exemplo.com', '11988887777');

INSERT INTO T_CLYVO_RESPONSAVEL (nm_responsavel, cpf, dt_nascimento, email, num_celular)
VALUES ('Carlos Eduardo Lima', '111.222.333-44', DATE '1985-09-23', 'carlos.lima@exemplo.com', '11977776666');

INSERT INTO T_CLYVO_ANIMAL (nm_animal, idade, especie, raca, sexo, dt_nascimento, peso, fk_id_responsavel)
VALUES (
    'Thor',
    3,
    'Canina',
    'Labrador',
    'M',
    DATE '2023-02-15',
    28.5,
    (SELECT id_responsavel FROM T_CLYVO_RESPONSAVEL WHERE email = 'ana.souza@exemplo.com')
);

INSERT INTO T_CLYVO_ANIMAL (nm_animal, idade, especie, raca, sexo, dt_nascimento, peso, fk_id_responsavel)
VALUES (
    'Mia',
    2,
    'Felina',
    'Siames',
    'F',
    DATE '2024-01-10',
    4.2,
    (SELECT id_responsavel FROM T_CLYVO_RESPONSAVEL WHERE email = 'carlos.lima@exemplo.com')
);

COMMIT;
